---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aesbjgvuu0pm/public_html/
    - /bin/rm -Rf /home/aesbjgvuu0pm/public_html/*
    - /bin/cp Home.html $DEPLOYPATH
    - /bin/cp Knowledge.html $DEPLOYPATH
    - /bin/cp projects.html $DEPLOYPATH
